### ISSUE TITLE
Add test runner to the CI

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#10]

**Comment by FabriDamazio** [comment]
I would like to try this one @BrooklinJazz

**Comment by BrooklinJazz** [comment]
Great! We have this working on DockYard Academy if you want to use it as an example

**Comment by FabriDamazio** [comment]
Hey @BrooklinJazz !
I've made an Action on my fork, can you check if that is what you are looking for?
https://github.com/FabriDamazio/elixir_newbie_website/actions

Waiting your response to create a PR.

**Comment by BrooklinJazz** [comment]
@FabriDamazio Looks correct to me!
