### ISSUE TITLE
Add author attribution to blog posts

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#12]

**Comment by BrooklinJazz** [comment]
How medium adds author attribution: https://brooklinmyers.medium.com/pagination-and-infinite-scroll-in-phoenix-d2a5f9bac5d6

**Comment by BrooklinJazz** [comment]
Author attribution should include:
- author name
- (optional) author picture
- perhaps (optional) lists or call to action

**Comment by BrooklinJazz** [comment]
![image](https://user-images.githubusercontent.com/14877564/175428722-3eb3aa41-60c8-4c96-a77f-965388d61fb1.png)

**Comment by BrooklinJazz** [comment]
![image](https://user-images.githubusercontent.com/14877564/175428748-f786004a-86a1-45d7-bf0d-521d93a7c659.png)

**Comment by FabriDamazio** [comment]
Hey @BrooklinJazz 
I will give a try on this one!

**Comment by FabriDamazio** [comment]
Is it good for an initial version?

![image](https://user-images.githubusercontent.com/3181570/189945510-6757917f-122d-4402-944f-045ba8e7c598.png)

**Comment by FabriDamazio** [comment]
another option
![image](https://user-images.githubusercontent.com/3181570/189961893-53ae19f6-08ea-4509-bd2c-8426223b14d6.png)

**Comment by BrooklinJazz** [comment]
> another option
> ![image](https://user-images.githubusercontent.com/3181570/189961893-53ae19f6-08ea-4509-bd2c-8426223b14d6.png)
> 

Apologies for my late response! I love the second option with the white background. Great work!
