### ISSUE TITLE
Add Links To Home Page

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#14]
![image](https://user-images.githubusercontent.com/14877564/177216355-b7584ae5-97ef-4432-b00d-352344208f06.png)

**Comment by BrooklinJazz** [comment]
Currently these links have hover styling that implies they are clickable, but do not link to Linkedin, Twitter, or an Email application

**Comment by J0hn1975** [comment]
Hi Brooklin Jazz,

I can take a look at this issue for you.

Let me know you if would like me to proceed.

Kind regards
John Wrafter

**Comment by BrooklinJazz** [comment]
Hi John! Feel free to! Let me know if there's any trouble and I can help

**Comment by BrooklinJazz** [comment]
Hi @J0hn1975!

That's exactly right! Can you make a PR?

**Comment by BrooklinJazz** [comment]
Hi @J0hn1975 I don't see any pull request: https://github.com/BrooklinJazz/elixir_newbie_website/pulls

Let me know if I can help, happy to pair program with you over a call to make the PR.

The steps are:
1. fork the repo (already done)
2. create a new branch (usually named after the issue # or the feature)
3. make and commit your changes
4. push the changes to your remote fork
5. Create a new pull request with the compare branch being your fork's remote branch: https://github.com/BrooklinJazz/elixir_newbie_website/compare

**Comment by BrooklinJazz** [comment]
I believe you already have the branch, you just need to make the PR. https://github.com/J0hn1975/elixir_newbie_website/compare/Add-Links-To-Home-Page-%2314

**Comment by J0hn1975** [comment]
Hi Brooklin,

Try again now

**Comment by FabriDamazio** [comment]
Hello @J0hn1975 and @BrooklinJazz,

This issue has been inactive for a month so I took the liberty of creating the PR.
Basically it's the @J0hn1975 implementation. I Just tested locally and created the PR.

Thanks @J0hn1975 for the implementation! Feel free to message me if you need any help with the PR creation flow.

Hope it helps!
