### ISSUE TITLE
Add hover styles to tags on Blog List page

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#15]
![image](https://user-images.githubusercontent.com/14877564/177216621-cabb4c38-ac15-46d9-a7a0-5fdee46fb042.png)

These tags should have hover styles, both when enabled and disabled.

**Comment by FloatingDorito** [comment]
Hi! I am interested to help fix the issue, can you assist me after I pull the code to visual studio code and am able to run the program, and guide me towards the files that I need to modify the code on?

**Comment by BrooklinJazz** [comment]
Absolutely! let me know if you get stuck at any point and I can help. I'm also happy to pair program with you if you'd prefer to do a video + screen share together.

To add this feature, you'll want to see the file `blog_list.ex`. on line 80 there's a paragraph tag for the element seen in the example.

```elixir
<p :on-click="toggle-tag" phx-value-tag={tag} class={"flex items-center h-8 mb-4 px-6 mr-6 rounded-full cursor-pointer", "bg-secondary": tag in @selected_tags, "bg-secondary/[0.3]": tag not in @selected_tags}>{String.replace(tag, "_", " ")}</p>
```

Likely we need to add a tailwind hover style: https://tailwindcss.com/docs/hover-focus-and-other-states

Something like `hover:bg-secondary[0.2]`.
I'm not certain exactly what background color or style will look good, so feel free to use your best judgment and creativity!

To ensure the feature works as expected, hover your cursor over the element and ensure the hover style applies.

Reach out if I can help!

**Comment by FloatingDorito** [comment]
Thank you very much for the help!
The issue I am facing right now is cloning the repo using github dekstop
This is the issue I am facing
![image](https://user-images.githubusercontent.com/52376777/177928879-f6ab8ef8-b59f-4c66-be0b-de22f01b8b50.png)
This is what happens when I 'Retry Clone'
![image](https://user-images.githubusercontent.com/52376777/177928949-371363b9-0d93-4f12-bc12-31f35e1ef3c6.png)
I removed the folder from local and retry again, but it still showed me this result

**Comment by FloatingDorito** [comment]
May I know your timezone so I can communicate with you well?

**Comment by BrooklinJazz** [comment]
I'm PT so about to go to bed but will try to respond as soon as I can.

Interesting that cloning is the issue 🤔 I might recommend trying the command line instead of using github desktop.

You'll also want to make a fork before cloning the repo (open source projects don't accept direct PRs unless you have contributor privledges)

If you prefer using github desktop, perhaps try cloning under a different project name.

If none of that works feel free to send me an email brooklin@elixirnewbie.com and I'll send you a link to book some time to sit down and fix this together over a video call.

**Comment by FloatingDorito** [comment]
Thank you very much, rest well, I will try and work on it again tonight

**Comment by FloatingDorito** [comment]
@BrooklinJazz Hi! I've faced an issue and emailed you, please have a look, thank you!
