### ISSUE TITLE
Add Author Attribution to Blog List page

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#16]

**Comment by FabriDamazio** [comment]
@BrooklinJazz i've maide a naive implementation of this feature. I'm not sure about the visual, but its easy to change if needed.

Here's an exemple:

![image](https://user-images.githubusercontent.com/3181570/182040464-f5ad1f01-ee19-413e-8562-0d0c13c38752.png)

What do you think?

**Comment by FabriDamazio** [comment]
I've made the changes you pointed out in the PR.
Now the default value os `author_name` is Brooklin Myers and the name is floating right.

![image](https://user-images.githubusercontent.com/3181570/182047407-7f24c1cf-46d9-43a3-bb41-7b7ee87ba397.png)
