### ISSUE TITLE
#ElixirNewbie Twitter Feed Integration

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#19]
Create a page that displays tweets for the hashtag ElixirNewbie similar to https://elixirstatus.com/

**Comment by FabriDamazio** [comment]
Should we consume twitter API filtering by #ElixirNewbie and display it in a reversed cronological order every time page is opened?
I think i can work in something like this if you agreed.

**Comment by BrooklinJazz** [comment]
That's exactly how I think we should start. 

We might want to consider using caching or a db but I think starting by calling the api and displaying the results is perfect.

**Comment by FabriDamazio** [comment]
> how I think we should start.
> 
> We might want to consider using caching or a db but I think starting by calling the api and displaying the results is perfect.

Perfect! I will start work on it this week.

**Comment by BrooklinJazz** [comment]
Let me know if I can help! I'd be happy to pair program or help however I can.

**Comment by FabriDamazio** [comment]
> Let me know if I can help! I'd be happy to pair program or help however I can.

I would love to pair up one of these days!

**Comment by BrooklinJazz** [comment]
> > Let me know if I can help! I'd be happy to pair program or help however I can.
> 
> I would love to pair up one of these days!

Feel free to use this link to schedule a time with me! https://calendly.com/elixirnewbie/pair-programming lmk of the times don't work and I can provide more flexible options.

**Comment by FabriDamazio** [comment]
@BrooklinJazz  I was thinking about the page visuals (something inspired by elixirstatus as you said).
What do you think about something like:
![image](https://user-images.githubusercontent.com/3181570/193645924-b419b30f-ceea-41a3-856c-a07894f09458.png)

where all the post area will be clickable and when clicked will open the tweet page in a new tab.

i've already made a twitter module to search last week tweets (API limitation) by a hashtag. Response example:
![image](https://user-images.githubusercontent.com/3181570/193647515-df9ea55a-7fa4-4e47-abc2-cee27a2b6eee.png)

**Comment by BrooklinJazz** [comment]
Fantastic work! I think this looks excellent!!!! Please let me know if I can help, or feel free to use that link above to schedule time with me if you'd like to pair.

**Comment by FabriDamazio** [comment]
> Fantastic work! I think this looks excellent!!!! Please let me know if I can help, or feel free to use that link above to schedule time with me if you'd like to pair.

Scheduled for 18:00 (gmt -3) today. Should i receive a link by email?

**Comment by FabriDamazio** [comment]
Hello @BrooklinJazz 

I was travelling last week. Sorry for the delay.
I need two informations: 

1. the text for the link on menu to twitter feed. Maybe just "Twitter" or "#ElixirNewbie"
![image](https://user-images.githubusercontent.com/3181570/196309658-3536d141-0aa5-4353-b3df-a2694bbc1f9e.png)

2. The twitter feed page Title text
![image](https://user-images.githubusercontent.com/3181570/196309792-63600f6f-548a-4500-892f-e55a0c0ba3ee.png)

Can you please help me?

**Comment by FabriDamazio** [comment]
Sugestion:

![image](https://user-images.githubusercontent.com/3181570/196520195-441d2ba5-ed1a-4094-ae37-677d97280e44.png)

**Comment by BrooklinJazz** [comment]
#ElixirNewbie is great! Make sure you change that title that says #TwitterNewbie to #ElixirNewbie

**Comment by FabriDamazio** [comment]
> 

Oh sure! XD
