### ISSUE TITLE
Create an Elixir themed Words Per Minute Game

### ISSUE THREAD

**Issue by BrooklinJazz** [BrooklinJazz/elixir_newbie_website#28]
I'd like to create a learning resource that helps developers learn Elixir syntax through repetition. Similar to typing test games such as https://www.keyhero.com/. the player would get a prompt such as

```elixir
Enum.map(1..10, fn integer -> integer * 2 end)
```

They then have to type the provided prompt. It will highlight red if they type a character incorrectly. When the type the last character in the prompt then it submits the prompt (and shows the evaluated result for extra fun)

This has room for additional features such as:
- tracking score
- syntax highlighting
- typing the prompt inline rather than in a separate text box
- turning on and off different syntax features for the prompt. For example, you could select `comprehensions` and the prompts would all be prompts with comprehensions only to target specific language features.

Makes sense this would be a LiveView that handles event when the user enters input and alters the display accordingly.

**Comment by FabriDamazio** [comment]
i would love to create this game if you don't mind :smile:

**Comment by BrooklinJazz** [comment]
I have a student working on this, maybe you can collaborate together 🤔 I'm going to close this issue since it's going to be their capstone project for DockYard Academy.

**Comment by BrooklinJazz** [comment]
@FabriDamazio If you're looking for project ideas, I have a few on my backburner.
- Elixir Newbie Discord Bot (rubber ducky which would provide Elixir doc suggestions and hints when students ask questions). This would be a fantastic resource for DockYard Academy and other Elixir Discords. I have a list of feature ideas.
- An ExUnit Formatter for Livebook
- Help out NotesClub: https://github.com/notesclub/notesclub/issues/42 they are a great project.

I'm also open to suggestions for Elixir Newbie :)

**Comment by fabrithedev** [comment]
> @FabriDamazio If you're looking for project ideas, I have a few on my backburner.
> 
> * Elixir Newbie Discord Bot (rubber ducky which would provide Elixir doc suggestions and hints when students ask questions). This would be a fantastic resource for DockYard Academy and other Elixir Discords. I have a list of feature ideas.
> * An ExUnit Formatter for Livebook
> * Help out NotesClub: [Add infinite scroll notesclub/notesclub#42](https://github.com/notesclub/notesclub/issues/42) they are a great project.
> 
> I'm also open to suggestions for Elixir Newbie :)

Thanks for the suggestions, i'll take a look into NotesClub and see what can i help! Looking forward to pair again!
