### ISSUE TITLE
Add page titles for individual Blog and Podcast posts

### ISSUE THREAD

**Issue by w0rd-driven** [BrooklinJazz/elixir_newbie_website#5]
When loading multiple posts it becomes difficult to distinguish which tab belongs to the post I'm looking for. Loading up say https://www.elixirnewbie.com/blog/writing-tests-in-livebook and https://www.elixirnewbie.com/blog/the-20%25-of-elixir-syntax-you-need-to-read-80%25-of-elixir-code, both titles show as `Blog · Elixir Newbie`.

If we change the `mount` function in `lib/elixir_newbie_web/live/blog_show.ex` to assign the page title as `page_title: blog.title`, the title shows as `The ‘use’ Macro in Elixir. · Elixir Newbie`. Punctuation/periods are in quite a few titles that could likely be removed.

I can do the PR if you didn't mind the change. I wasn't sure if you wanted the punctuation changed as well or if that's just my nitpick. I also just realized podcasts follow the same format and could likely use the same treatment.

**Comment by BrooklinJazz** [comment]
Hey @w0rd-driven ! I'm so sorry for the very very late response!

If you're still interested this would make a great PR. I think it may also be a great issue to tackle for the Elixiteers group.

**Comment by w0rd-driven** [comment]
Hey @BrooklinJazz, no worries I know you're pretty busy. I'm okay with deferring the PR to the Elixiteers group.

I don't know if it's too easy with a solution somewhat worked out but there could be a deeper lesson in tinkering with what gets displayed. There could also be other quality of life improvements I haven't thought of.

I'm personally down with any changes to the site as part of the group. I wanna help other newbies in any way I can, even if something seems trivial.

**Comment by BrooklinJazz** [comment]
It didn't get voted for todays topic, so I'd say feel free to make a PR if
you'd like.

If not we can let it sit for a future session or new contributor.
